version: "3.7"

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: T4cwGK3q5NdR3vMz
            MYSQL_DATABASE: vscode4teach
            MYSQL_USER: vscode4teach
            MYSQL_PASSWORD: AvScnGQp5e4GHnd
    app:
        image: vscode4teaching/vscode4teaching:1.1.0
        links:
            - db
        depends_on:
            - db
        ports:
            - "8080:8080"
        restart: always
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db/vscode4teach?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            SPRING_DATASOURCE_USERNAME: vscode4teach
            SPRING_DATASOURCE_PASSWORD: AvScnGQp5e4GHnd
