version: "3.9"

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
            MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    app:
        image: vscode4teaching/vscode4teaching:latest
        links:
            - db
        depends_on:
            - db
        env_file:
            - .env
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        volumes:
            - v4t-course:/app/${v4t-course}
        restart: always
volumes:
    db_data: {}
    v4t-course: {}
