name: vscode4teaching

services:
  app:
    image: vscode4teaching/vscode4teaching:3.0.0
    depends_on:
      - db
    env_file:
      - path: .env
        required: true
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - vscode4teaching-courses:${V4T_FILEDIRECTORY}
    restart: on-failure:6
  db:
    image: mysql:9.1.0
    restart: on-failure:3
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - vscode4teaching-db:/var/lib/mysql

volumes:
  vscode4teaching-courses:
  vscode4teaching-db:
